# Generated by Django 2.0.1 on 2018-01-09 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_yazhu'),
    ]

    operations = [
        migrations.AddField(
            model_name='yazhu',
            name='rej01',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='yazhu',
            name='rej02',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='yazhu',
            name='rej03',
            field=models.IntegerField(default=0),
        ),
    ]
