# Generated by Django 2.0.1 on 2018-01-12 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20180109_1656'),
    ]

    operations = [
        migrations.CreateModel(
            name='FtDev',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dev_date', models.DateTimeField(verbose_name='date published')),
                ('dev_duration', models.FloatField(verbose_name='hours')),
                ('dev_topic', models.CharField(default='.', max_length=500)),
                ('dev_description', models.CharField(default='.', max_length=500)),
                ('dev_review', models.CharField(default='.', max_length=500)),
            ],
        ),
    ]
