# Generated by Django 2.0.1 on 2018-01-12 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_ftdev'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ftdev',
            old_name='dev_date',
            new_name='dev_datetime',
        ),
    ]
